# Generated by Django 4.2 on 2023-04-27 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seashell_center', '0002_rename_name_centeruser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centeruser',
            old_name='username',
            new_name='name',
        ),
    ]
