# Generated by Django 4.2 on 2023-04-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seashell_center', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centeruser',
            old_name='name',
            new_name='username',
        ),
    ]
