# Generated by Django 4.2 on 2023-05-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seashell_center', '0003_rename_username_centeruser_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayexperience',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='message',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='seashell_center.tag'),
        ),
    ]
